### ISSUE TITLE
Upgrade to RTD theme v1.0.0

### ISSUE THREAD

**Issue by Paebbels** [buildthedocs/sphinx_btd_theme#6]
ReadTheDocs upgraded the theme to [version 1.0.0](https://github.com/readthedocs/sphinx_rtd_theme/releases/tag/1.0.0).

Can we/should we upgrade to 1.0.0 too?

**Comment by eine** [comment]
This is done since the begining of september, in practice:

![image](https://user-images.githubusercontent.com/6628437/142776710-138209c8-e53f-4d3c-a586-399115833e18.png)
